export enum USER_ACTION_TYPES {
  SET_USER = "user/SET_USER",
  SET_EMAIL = "user/SET_EMAIL",
  SET_TMP = "user/SET_TMP",
  SET_CART = "user/SET_CART",
  REMOVE_USER = "user/REMOVE_USER",
  REMOVE_TMP = "user/REMOVE_TMP",
  REMOVE_CART = "user/REMOVE_CART",
  UPDATE_USER = "user/UPDATE_USER",
}
